---
version: '3.7'
services:
  mongo-seed:
    image: fvilers/mongo-seed:1.0.0
    environment:
    - MONGO_HOST=mongo
    - MONGO_PORT=27017
    volumes:
    - ./data:/data
    command:
    - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"
    depends_on:
            - mongo
  mongo:
          image: mongo:latest
  server:
          image: benm96/paserver:v1
          depends_on:
                  - mongo
          ports:
                  - target: 8080
                    published: 8080
  client:
          image: benm96/paclient:v1
          depends_on:
                  - server
          ports:
                  - target: 3000
                    published: 3000
  nginx:
          image: benm96/panginx:2
          ports:
                  - target: 80
                    published: 80
          depends_on:
                  - server
                  - client
