apiVersion: v1
kind: Pod
metadata:
        name: mongo
spec:
        containers:
                - name: mongo
                  image: docker.io/library/mongo:latest
                  ports:
                          - containerPort: 27017
